# Generated by Django 5.1.7 on 2025-03-15 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedrijf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
                ('locatie', models.CharField(max_length=200)),
                ('technologieen', models.TextField(blank=True, null=True)),
                ('contactpersoon', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefoonnummer', models.CharField(blank=True, max_length=20, null=True)),
                ('is_samenwerkingsbedrijf', models.BooleanField(default=False)),
                ('is_potentieel_bedrijf', models.BooleanField(default=False)),
                ('beoordeling', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coördinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('omschrijving', models.TextField()),
                ('technologieen', models.TextField(blank=True, null=True)),
                ('startdatum', models.DateField(blank=True, null=True)),
                ('einddatum', models.DateField(blank=True, null=True)),
                ('beschikbare_plaatsen', models.IntegerField(default=1)),
                ('bedrijf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.bedrijf')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programmeertalen', models.TextField(blank=True, null=True)),
                ('werkvoorkeuren', models.TextField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('ervaring', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('motivatiebrief', models.FileField(blank=True, null=True, upload_to='motivatiebrieven/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('studenten', models.ManyToManyField(blank=True, to='stages.student')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beoordeling', models.IntegerField()),
                ('opmerkingen', models.TextField(blank=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.student')),
            ],
        ),
        migrations.CreateModel(
            name='Benadering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(auto_now_add=True)),
                ('contactwijze', models.CharField(max_length=100)),
                ('cv', models.FileField(blank=True, null=True, upload_to='benaderingen/cvs/')),
                ('motivatiebrief', models.FileField(blank=True, null=True, upload_to='benaderingen/motivatiebrieven/')),
                ('opmerkingen', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Benaderd', max_length=100)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.student')),
            ],
        ),
    ]
